### ISSUE TITLE
Unchecked runtime.lastError while running tabs.insertCSS: Failed to load file:

### ISSUE THREAD

**Issue by lancejpollard** [diffsky/chromedotfiles#2]
Adding console.log to `background.js`, when going to create this issue it says:

```
// i'm logging here
tab: https://github.com/diffsky/chromedotfiles/issues/new
match: Object {protocol: "https:", host: "github.com", hostname: "github.com", port: undefined, pathname: "/diffsky/chromedotfiles/issues/new"…}

// chrome throws these errors
extensions::sendRequest:82 Unchecked runtime.lastError while running tabs.insertCSS: Failed to load file: "chromedotfiles/github.com.css". 
    at chrome-extension://hocrtbokejcqajcfomloelehcgookikb/background.js:23:17
extensions::sendRequest:82 Unchecked runtime.lastError while running tabs.executeScript: Failed to load file: "chromedotfiles/github.com.js". 
    at chrome-extension://hocrtbokejcqajcfomloelehcgookikb/background.js:26:17
```

I tried placing a file in 2 different places to see if it'd work, but doesn't seem to:

```
~/.chromedotfiles/github.com.js
~/chromedotfiles/github.com.js
```

Is there any other setup I have to do? Do you have to do anything with certificates like with dotjs?

Does it depend on a specific version of chrome or operating system? I haven't updated my mac in a while, still using 10.9.2, not sure if that's a problem.

Would love to get this working :)

**Comment by lancejpollard** [comment]
ah, you just need to put the files inside:

```
diffsky/chromedotfiles/chromedotfiles/github.com.js
```
